name: Build Sriracha App

on:
  push:
    branches:
      - '**'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Rebuild macOS App Icon
        run: |
          mkdir -p packaging/icon.iconset
          sips -z 512 512 packaging/appicon.png --out packaging/icon.iconset/icon_512x512.png
          iconutil -c icns packaging/icon.iconset -o packaging/appicon.icns
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm --clean sriracha.spec
      - name: Create DMG
        run: |
          hdiutil create -volname Sriracha -srcfolder dist/sriracha.app -ov -format UDZO dist/Sriracha.dmg
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sriracha-macOS
          path: dist/Sriracha.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm --clean sriracha.spec
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sriracha-Windows
          path: dist/sriracha/sriracha.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm --clean sriracha.spec
      - name: Install AppImage tools
        run: |
          sudo apt-get update
          sudo apt-get install -y appimagetool
          wget -O linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
      - name: Create AppImage
        run: |
          ./linuxdeploy-x86_64.AppImage --appdir dist/sriracha.AppDir -e dist/sriracha/sriracha -i packaging/appicon.png -d packaging/sriracha.desktop --output appimage
      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sriracha-Linux
          path: '*.AppImage'
