name: Build Sriracha App

on:
  push:
    branches:
      - "**"

jobs:
  build-macos:
    runs-on: macos-latest
    if: |
      github.event.head_commit.message == null ||
      contains(github.event.head_commit.message, '[build-macos]') ||
      !contains(github.event.head_commit.message, '[build-')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: |
          source .venv/bin/activate
          pyinstaller --noconfirm --clean sriracha-macos.spec
      - name: Create DMG
        run: |
          hdiutil create -volname Sriracha -srcfolder dist/sriracha.app -ov -format UDZO dist/Sriracha.dmg
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sriracha-macOS
          path: dist/Sriracha.dmg

  build-windows:
    runs-on: windows-latest
    if: |
      github.event.head_commit.message == null ||
      contains(github.event.head_commit.message, '[build-windows]') ||
      !contains(github.event.head_commit.message, '[build-')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/Scripts/activate
          pip install -r requirements.txt
      - name: Install VC++ Redistributable
        shell: powershell
        run: |
          $vcRedistUrl = "https://aka.ms/vs/17/release/vc_redist.x64.exe"
          $vcRedistPath = "$env:TEMP\vc_redist.x64.exe"
          Invoke-WebRequest -Uri $vcRedistUrl -OutFile $vcRedistPath
          Start-Process -FilePath $vcRedistPath -ArgumentList "/install", "/quiet", "/norestart" -Wait
      - name: Build with PyInstaller
        run: |
          .venv/Scripts/activate
          pyinstaller --noconfirm sriracha-windows.spec
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sriracha-Windows
          path: dist/sriracha.exe

  build-linux:
    runs-on: ubuntu-latest
    if: |
      github.event.head_commit.message == null ||
      contains(github.event.head_commit.message, '[build-linux]') ||
      !contains(github.event.head_commit.message, '[build-')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install AppImage tools
        run: |
          sudo apt update
          sudo apt install -y libfuse2 imagemagick libgtk-3-dev
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U \
            -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-24.04 \
            wxPython
          pip install -r requirements.txt
      - name: Create application icon
        run: |
          convert packaging/sriracha.png -resize 256x256 packaging/linux/appimage/sriracha.png
      - name: Build with PyInstaller
        run: |
          source .venv/bin/activate
          pyinstaller --noconfirm --clean sriracha-linux.spec
      - name: Package as AppImage
        run: |
          mkdir packaging/linux/appimage/Sriracha.AppDir/opt
          mv dist/sriracha packaging/linux/appimage/Sriracha.AppDir/opt
          convert packaging/appicon.png -resize 256x256 packaging/linux/appimage/sriracha.png
          (cd packaging/linux/appimage/Sriracha.AppDir && ln -s opt/sriracha/sriracha AppRun)
          (cd packaging/linux/appimage/Sriracha.AppDir && ln -s usr/share/applications/io.github.cameronkerr.sriracha.desktop .)
          ./appimagetool packaging/linux/appimage/Sriracha.AppDir
      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sriracha-Linux
          path: "packaging/linux/appimage/Sriracha*.AppImage"
